In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv(r"C:\Users\Divya\Downloads\climate_nasa.csv")

In [4]:
df

,date,likesCount,profileName,commentsCount,text
0,2022-09-07T17:12:32.000Z,2,4dca617d86b3fdce80ba7e81fb16e048c9cd9798cdfd6d...,NaN,Neat comparison I have not heard it before.\n ...
1,2022-09-08T14:51:13.000Z,0,518ab97f2d115ba5b6f03b2fba2ef2b120540c9681288b...,NaN,An excellent way to visualise the invisible! T...
2,2022-09-07T17:19:41.000Z,1,d82e8e24eb633fd625b0aef9b3cb625cfb044ceb8483e1...,3.0,Does the CO2/ghg in the troposphere affect the...
3,2022-09-08T00:51:30.000Z,4,37a509fa0b5177a2233c7e2d0e2b2d6916695fa9fba3f2...,NaN,excellent post! I defo feel the difference - o...
4,2022-09-07T19:06:20.000Z,16,e54fbbd42a729af9d04d9a5cc1f9bbfe8081a31c219ecb...,26.0,"Yes, and carbon dioxide does not harm the Eart..."
...,...,...,...,...,...
517,2022-12-22T17:21:37.000Z,0,9e17b1a6422032d47472f0216c73aafda7587e302eed5e...,NaN,One can only hope for a peak 😞
518,2022-12-22T17:19:51.000Z,1,48e55d898603a136aefc44771f248bffd67242583a462a...,5.0,what is the error margin for the temperature e...
519,2022-12-22T17:12:57.000Z,3,ca5d2611814cf8c9844ed06d9916d876d2dba94dac5ff2...,NaN,We all should volenteerly help in reducing Glo...
520,2022-12-22T17:01:12.000Z,1,a87c8aea74c9b97002b368d6143ce9c2809dcaec3103fb...,NaN,Sergio Yepes
521,2022-12-22T17:00:08.000Z,12,cc70f6c9dcc2637b1c5fd90046834612627c752b828cb4...,1.0,"We're experiencing severe, abnormal weather pa..."

In [5]:
df.head()

,date,likesCount,profileName,commentsCount,text
0,2022-09-07T17:12:32.000Z,2,4dca617d86b3fdce80ba7e81fb16e048c9cd9798cdfd6d...,NaN,Neat comparison I have not heard it before.\n ...
1,2022-09-08T14:51:13.000Z,0,518ab97f2d115ba5b6f03b2fba2ef2b120540c9681288b...,NaN,An excellent way to visualise the invisible! T...
2,2022-09-07T17:19:41.000Z,1,d82e8e24eb633fd625b0aef9b3cb625cfb044ceb8483e1...,3.0,Does the CO2/ghg in the troposphere affect the...
3,2022-09-08T00:51:30.000Z,4,37a509fa0b5177a2233c7e2d0e2b2d6916695fa9fba3f2...,NaN,excellent post! I defo feel the difference - o...
4,2022-09-07T19:06:20.000Z,16,e54fbbd42a729af9d04d9a5cc1f9bbfe8081a31c219ecb...,26.0,"Yes, and carbon dioxide does not harm the Eart..."

In [6]:
df.tail()

,date,likesCount,profileName,commentsCount,text
517,2022-12-22T17:21:37.000Z,0,9e17b1a6422032d47472f0216c73aafda7587e302eed5e...,NaN,One can only hope for a peak 😞
518,2022-12-22T17:19:51.000Z,1,48e55d898603a136aefc44771f248bffd67242583a462a...,5.0,what is the error margin for the temperature e...
519,2022-12-22T17:12:57.000Z,3,ca5d2611814cf8c9844ed06d9916d876d2dba94dac5ff2...,NaN,We all should volenteerly help in reducing Glo...
520,2022-12-22T17:01:12.000Z,1,a87c8aea74c9b97002b368d6143ce9c2809dcaec3103fb...,NaN,Sergio Yepes
521,2022-12-22T17:00:08.000Z,12,cc70f6c9dcc2637b1c5fd90046834612627c752b828cb4...,1.0,"We're experiencing severe, abnormal weather pa..."

In [7]:
df.shape

(522, 5)

In [8]:
df.describe

<bound method NDFrame.describe of                          date  likesCount  \
0    2022-09-07T17:12:32.000Z           2
1    2022-09-08T14:51:13.000Z           0
2    2022-09-07T17:19:41.000Z           1
3    2022-09-08T00:51:30.000Z           4
4    2022-09-07T19:06:20.000Z          16
..                        ...         ...
517  2022-12-22T17:21:37.000Z           0
518  2022-12-22T17:19:51.000Z           1
519  2022-12-22T17:12:57.000Z           3
520  2022-12-22T17:01:12.000Z           1
521  2022-12-22T17:00:08.000Z          12

                                           profileName  commentsCount  \
0    4dca617d86b3fdce80ba7e81fb16e048c9cd9798cdfd6d...            NaN
1    518ab97f2d115ba5b6f03b2fba2ef2b120540c9681288b...            NaN
2    d82e8e24eb633fd625b0aef9b3cb625cfb044ceb8483e1...            3.0
3    37a509fa0b5177a2233c7e2d0e2b2d6916695fa9fba3f2...            NaN
4    e54fbbd42a729af9d04d9a5cc1f9bbfe8081a31c219ecb...           26.0
..                                                 ...            ...
517  9e17b1a6422032d47472f0216c73aafda7587e302eed5e...            NaN
518  48e55d898603a136aefc44771f248bffd67242583a462a...            5.0
519  ca5d2611814cf8c9844ed06d9916d876d2dba94dac5ff2...            NaN
520  a87c8aea74c9b97002b368d6143ce9c2809dcaec3103fb...            NaN
521  cc70f6c9dcc2637b1c5fd90046834612627c752b828cb4...            1.0

                                                  text
0    Neat comparison I have not heard it before.\n ...
1    An excellent way to visualise the invisible! T...
2    Does the CO2/ghg in the troposphere affect the...
3    excellent post! I defo feel the difference - o...
4    Yes, and carbon dioxide does not harm the Eart...
..                                                 ...
517                     One can only hope for a peak 😞
518  what is the error margin for the temperature e...
519  We all should volenteerly help in reducing Glo...
520                                       Sergio Yepes
521  We're experiencing severe, abnormal weather pa...

[522 rows x 5 columns]>

In [9]:
df.info

<bound method DataFrame.info of                          date  likesCount  \
0    2022-09-07T17:12:32.000Z           2
1    2022-09-08T14:51:13.000Z           0
2    2022-09-07T17:19:41.000Z           1
3    2022-09-08T00:51:30.000Z           4
4    2022-09-07T19:06:20.000Z          16
..                        ...         ...
517  2022-12-22T17:21:37.000Z           0
518  2022-12-22T17:19:51.000Z           1
519  2022-12-22T17:12:57.000Z           3
520  2022-12-22T17:01:12.000Z           1
521  2022-12-22T17:00:08.000Z          12

                                           profileName  commentsCount  \
0    4dca617d86b3fdce80ba7e81fb16e048c9cd9798cdfd6d...            NaN
1    518ab97f2d115ba5b6f03b2fba2ef2b120540c9681288b...            NaN
2    d82e8e24eb633fd625b0aef9b3cb625cfb044ceb8483e1...            3.0
3    37a509fa0b5177a2233c7e2d0e2b2d6916695fa9fba3f2...            NaN
4    e54fbbd42a729af9d04d9a5cc1f9bbfe8081a31c219ecb...           26.0
..                                                 ...            ...
517  9e17b1a6422032d47472f0216c73aafda7587e302eed5e...            NaN
518  48e55d898603a136aefc44771f248bffd67242583a462a...            5.0
519  ca5d2611814cf8c9844ed06d9916d876d2dba94dac5ff2...            NaN
520  a87c8aea74c9b97002b368d6143ce9c2809dcaec3103fb...            NaN
521  cc70f6c9dcc2637b1c5fd90046834612627c752b828cb4...            1.0

                                                  text
0    Neat comparison I have not heard it before.\n ...
1    An excellent way to visualise the invisible! T...
2    Does the CO2/ghg in the troposphere affect the...
3    excellent post! I defo feel the difference - o...
4    Yes, and carbon dioxide does not harm the Eart...
..                                                 ...
517                     One can only hope for a peak 😞
518  what is the error margin for the temperature e...
519  We all should volenteerly help in reducing Glo...
520                                       Sergio Yepes
521  We're experiencing severe, abnormal weather pa...

[522 rows x 5 columns]>

In [10]:
df.dtypes

date              object
likesCount         int64
profileName       object
commentsCount    float64
text              object
dtype: object

In [12]:
df.isnull().sum()

date               0
likesCount         0
profileName        0
commentsCount    278
text              18
dtype: int64